"""Database access, dialect-aware.

SQLite locally (so tests and the offline demo need no network), Postgres in the
cloud. One schema file serves both: the handful of genuine dialect differences
are rewritten here rather than maintained as two drifting copies.

Application SQL is written portably -- `?` placeholders, `ON CONFLICT DO
NOTHING`, and `RETURNING id` instead of lastrowid, all of which both engines
support.
"""
from __future__ import annotations

import os
import re
import sqlite3
import sys
from pathlib import Path
from typing import Any, Iterable

from .config import settings

SCHEMA_FILE = Path(__file__).with_name("schema.sql")


def _database_url() -> str | None:
    url = os.getenv("DATABASE_URL", "").strip()
    return url or None


def to_postgres(sql: str) -> str:
    """Rewrite the SQLite-flavoured schema for Postgres."""
    sql = re.sub(r"^\s*PRAGMA[^;]*;\s*$", "", sql, flags=re.MULTILINE)
    sql = sql.replace(
        "INTEGER PRIMARY KEY", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    )
    sql = sql.replace(") WITHOUT ROWID;", ");")
    sql = re.sub(r"\bREAL\b", "DOUBLE PRECISION", sql)
    return sql


class Cursor:
    """Thin wrapper giving both drivers the same surface: `?` placeholders and
    dict-like rows."""

    def __init__(self, raw, is_pg: bool):
        self._raw = raw
        self._is_pg = is_pg

    def fetchone(self):
        row = self._raw.fetchone()
        return _Row(row, self._raw) if (row is not None and self._is_pg) else row

    def fetchall(self):
        rows = self._raw.fetchall()
        return [_Row(r, self._raw) for r in rows] if self._is_pg else rows

    def __iter__(self):
        return iter(self.fetchall())

    @property
    def lastrowid(self):
        return self._raw.lastrowid


class _Row:
    """Index-or-name access over a psycopg tuple row."""

    __slots__ = ("_v", "_names")

    def __init__(self, values, cursor):
        self._v = values
        self._names = [d.name for d in cursor.description]

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._v[key]
        return self._v[self._names.index(key)]

    def get(self, key, default=None):
        try:
            return self[key]
        except ValueError:
            return default

    def keys(self):
        return list(self._names)


class Database:
    def __init__(self, url: str | None = None, path: Path | None = None):
        # An explicit path means "use SQLite here" -- tests and the offline demo
        # must not silently reach a cloud database because DATABASE_URL is set.
        self.url = url or (None if path is not None else _database_url())
        self.is_postgres = bool(self.url)
        if self.is_postgres:
            import psycopg

            # prepare_threshold=None is required by Supabase's transaction pooler,
            # which cannot carry prepared statements across pooled connections.
            self._conn = psycopg.connect(self.url, prepare_threshold=None, autocommit=False)
        else:
            p = Path(path or settings.db_path)
            p.parent.mkdir(parents=True, exist_ok=True)
            self._conn = sqlite3.connect(p)
            self._conn.row_factory = sqlite3.Row
            self._conn.execute("PRAGMA foreign_keys = ON")

    def execute(self, sql: str, params: Iterable[Any] = ()) -> Cursor:
        if self.is_postgres:
            cur = self._conn.cursor()
            cur.execute(sql.replace("?", "%s"), tuple(params))
            return Cursor(cur, True)
        return Cursor(self._conn.execute(sql, tuple(params)), False)

    def insert(self, sql: str, params: Iterable[Any] = ()) -> int:
        """INSERT returning the new id, portably."""
        if "returning" not in sql.lower():
            sql = sql.rstrip().rstrip(";") + " RETURNING id"
        row = self.execute(sql, params).fetchone()
        return int(row[0])

    def executescript(self, sql: str) -> None:
        if self.is_postgres:
            self._conn.execute(to_postgres(sql))
        else:
            self._conn.executescript(sql)
        self.commit()

    def commit(self) -> None:
        self._conn.commit()

    def close(self) -> None:
        self._conn.close()


def connect(path: Path | None = None, url: str | None = None) -> Database:
    return Database(url=url, path=path)


def init_schema(db: Database) -> None:
    db.executescript(SCHEMA_FILE.read_text())


def table_names(db: Database) -> list[str]:
    if db.is_postgres:
        rows = db.execute(
            "SELECT table_name AS name FROM information_schema.tables "
            "WHERE table_schema = 'public' ORDER BY table_name"
        ).fetchall()
    else:
        rows = db.execute(
            "SELECT name FROM sqlite_master WHERE type='table' "
            "AND name NOT LIKE 'sqlite_%' ORDER BY name"
        ).fetchall()
    return [r["name"] for r in rows]


def _cli(argv: list[str]) -> int:
    if not argv or argv[0] != "init":
        print("usage: python -m frontline.db init", file=sys.stderr)
        return 2
    db = connect()
    init_schema(db)
    names = table_names(db)
    where = "postgres" if db.is_postgres else str(settings.db_path)
    print(f"initialised {where}")
    print(f"{len(names)} tables: {', '.join(names)}")
    db.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(_cli(sys.argv[1:]))
